---
Devices:
  -vendor: Cisco
  os: IOS XR
  ram: 1024
  -vendor: Arista
  os: vEOS
  ram: 2048

- name: Show BGP Neigbors
  hosts: routers
  gather_facts: false

  tasks:
    - name: BGP Neighbors
      raw: "show ip bgp neighbors"
      register: output  <---capture output of task into variable
    - name: Printing Output
      debug: var=output.stdout_lines
