---
- name: Gather IOS-XE Facts
  hosts: sunbeam_switches
  connection: local
  tasks:
    - name: Gather IOS Facts
      ios_facts:
        provider: # used to provide connection info
          host: 192.168.1.1
          port: 22
          authorize: yes
          auth_pass: cisco
          username: cisco
          password: cisco
    - name: What is the IOS OS ver?
      debug:
        var: ansible_net_version

    - name: What is the hostname?
      debug:
        var: ansible_net_hostname