---
- name: fixing time at sites
  hosts: sunbeam_switches
  tasks:
    - name: update ntp on switches
      cisco.ios.ios_ntp:
        server: 192.168.229.1
        source_int: Vlan 10
        logging: false
        state: present