---
- name: Create loopbacks on device
  hosts: sunbeam_switches
  connection: local
  tasks:
    - name: Create loopback shell
      with_items: "{{local_loopback}}"
      nxos_interface:
        interface: "{{item_name}}"
        mode: layer3
        description: "{{item.desc}}"
        admin_state: ip

    - name: set new loopback configs
      with_items: "{{local_lookback}}"
      nxos_ip_interface:
        state: present
        interface: "{{item.name}}"
        version: v4
        addr: "{{item.ip_address}}"
        mask: "{{item.prefix}}"