---
- name: Demo ansible loops
  hosts: ubuntu
  become: yes
  tasks:
    - name: Create a file
      shell: echo 'Begin file' > /home/rsmetana/loops.txt
    - name: install packages
      shell: echo "{{item}} >> /home/rsmetana/loops.txt
      with_items: #with loop
        - vim
        - nano
        - python